### ISSUE TITLE
upsetjs and rmarkdown

### ISSUE THREAD

**Issue by Pierre9344** [upsetjs/upsetjs_r#27]
When I try to include more than two venn diagram with the upsetjs package, only the first two are created in the rendered document. If I try to create the venn from the code chunk in RStudio, every venn are create without error.

Is there a limit on the number of venn we can include in a single document? If so, is there a way to remove it?

**To Reproduce**

1.  Create a Rmarkdown document, I use the latest version of R and RStudio (with [Quarto](https://quarto.org/docs/get-started/) enabled)
2. Add 3 or more venn diagrams in one or different code chunk

```
upsetjsVennDiagram() %>%
  fromList(listInput) %>%
  chartVennLabels(title = "Venn diagram of the mixed batches analysis") %>%
  chartFontSizes(set.label = "13px", title = "18px") %>% interactiveChart()
```

3. Render the document to the html format.

**Expected behavior**

The document should normally show all the different venn diagrams. But in my case, only the first two are created

**Screenshots**
![2022-05-23_095125](https://user-images.githubusercontent.com/86181677/169770577-b1441159-34d7-436d-a4ef-a0e56f6a06b7.png)

**Context**

- Version: R 4.2 RStudio 2022.02.2+485
- Browser: 

**Additional context**

**Comment by sgratzl** [comment]
there is not intentional limit. Can you provide a sample rmarkdown file such that I can test the bug, please

**Comment by Pierre9344** [comment]
Okay, I first tried to just do the venn in different code chunk but it rendered normally. So I imitated my document and added title upside all the code chunk and I englobed the title and the code chunk with "::: panel-tabset" et ":::" those enable a tabset view in quarto (https://quarto.org/docs/interactive/layout.html#tabset-panel).  This time, I got the rendering error.

Here the qmd file and the html document that was rendered from it.

[test.zip](https://github.com/upsetjs/upsetjs_r/files/8752765/test.zip)

**Comment by sgratzl** [comment]
thx. 

it doesn't seem to be a problem of upsetjs but how the underlying htmlwidgets (https://quarto.org/docs/interactive/widgets/htmlwidgets.html) are implemented for tabset panel. Htmlwidgets have two methods for telling the widget (here upset) what the size is: 
 * during the creation of the widget
 * using a "resize" method
 
However, since the venn2 ... widgets are not visible by default, it will say during the creation that it should have a width and height of `0`. Moreover, when I switch tabs it won't be triggering the `resize` method with the right dimensions. Only if I change the size of my browser window it will trigger a resize. 

I would open an issue or vote on https://github.com/ramnathv/htmlwidgets/issues/392 which seems like the underlying problem.

**Comment by Pierre9344** [comment]
Ok thank you.
